name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 拉取代码
    - name: Checkout repository
      uses: actions/checkout@v4

    # 配置 JDK 17（Android Gradle Plugin 推荐的版本）
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # 安装 Android SDK
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    # 给 gradlew 授权
    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    # 生成 local.properties，让 Gradle 能找到 SDK
    - name: Setup local.properties
      run: echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties

    # 编译项目
    - name: Build with Gradle
      run: ./gradlew build
