name: Test Secrets

on:
  workflow_dispatch:  # 手动触发

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Verify GH_TOKEN
        run: |
          if [ -z "${{ secrets.GH_TOKEN }}" ]; then
            echo "❌ GH_TOKEN not found"
            exit 1
          else
            echo "✅ GH_TOKEN is set!"
          fi
